export const PagePath = {
    HOME: "/",
    ITEM: "/item",
    UPLOAD: '/upload-item',
    CART: "/cart",
    ALL_BRANDS: "/brands",
    HOT_DEAL: "/hot-deal",
    NEW_ITEM: "/new-item",
    GIFT: "/gift",
    BEST_SELLERS: "/best-sellers",
    LOGIN: "/login",
    REGISTER: "/register",
    CUSTOMER_SUPPORT: "/customer-support",
    SHOWROOM: "/showroom",
    PAYMENT: "/payment",
    PROFILE: "/profile",
    SEARCH_INVOICE: "/invoice",
}