export const URL = {
    ADD_NEW_ITEM: 'http://localhost:8080/api/v1/item',
    GET_ALL_ITEM: 'http://localhost:8080/api/v1/getAll',
    GET_DEFAULT_DATA: "http://localhost:8080/api/v1/getDefaultData",
    GET_ALL_BRAND: 'http://localhost:8080/api/v1/getAllBrand',
    GET_ALL_TYPE: 'http://localhost:8080/api/v1/getAllType',
    GET_ITEM_BY_ID: 'http://localhost:8080/api/v1/getOneItem',
    SEARCH_ITEM_BY_BRAND: 'http://localhost:8080/api/v1/search',
    GET_HOT_DEAL_ITEM: "http://localhost:8080/api/v1/hot-deal?page=",
    GET_ALL_HOT_DEAL_ITEM: "http://localhost:8080/api/v1/all-hot-item",
    GET_NEW_ITEM: "http://localhost:8080/api/v1/new-item?page=",
    GET_ALL_NEW_ITEM: "http://localhost:8080/api/v1/all-new-item",
    GET_BEST_SELLERS: "http://localhost:8080/api/v1/best-sellers?page=",
    GET_ALL_BEST_SELLERS: "http://localhost:8080/api/v1/all-best-sellers",
    GET_GIFT: "http://localhost:8080/api/v1/gift?page=",
    GET_ALL_GIFT: "http://localhost:8080/api/v1/all-gift",
    COUNT_ITEM_BY_TYPE_ID: "http://localhost:8080/api/v1/count-item-by-typeid?typeId=",
    COUNT_ITEM_BY_TYPE_ID_AND_BRAND: "http://localhost:8080/api/v1/count-item-by-typeid-brands",
    LOGIN: "http://localhost:8080/login",
    REGISTER: "http://localhost:8080/register",
    REFRESH_TOKEN: "http://localhost:8080/refreshToken",
    LOG_OUT: "http://localhost:8080/log-out",
    PAYMENT: "http://localhost:8080/api/v1/payment",
    CHANGE_CUSTOMER_INFO: "http://localhost:8080/info",
    GET_ALL_INVOICE: "http://localhost:8080/api/v1/getSomeInvoice",
    SEARCH_INVOICE_BY_CODE: "http://localhost:8080/api/v1/invoice",
    CANCEL_INVOICE_BY_CODE: "http://localhost:8080/api/v1/invoice"

}